"""initial migration

Revision ID: 633ca368515b
Revises: 7a98bda1bc70
Create Date: 2024-10-03 17:26:25.259339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633ca368515b'
down_revision = '7a98bda1bc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauthsession', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_oauthsession_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauthsession', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_oauthsession_user_id_users'), type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
